# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memes',
            name='tags',
            field=models.ManyToManyField(to='api.tags'),
        ),
    ]
