# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_memes_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memes',
            name='tags',
        ),
        migrations.AddField(
            model_name='tags',
            name='meme',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='api.memes'),
            preserve_default=False,
        ),
    ]
