# Generated by Django 2.0.1 on 2018-01-27 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180127_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('probability', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tags',
            name='meme',
        ),
        migrations.RenameModel(
            old_name='memes',
            new_name='Meme',
        ),
        migrations.DeleteModel(
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='meme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.Meme'),
        ),
    ]
